!function(){var q=null;window.PR_SHOULD_USE_CONTINUATION=!0;
(function(){function Q(b){function f(d){var a=d.charCodeAt(0);if(a!==92)return a;var g=d.charAt(1);return(a=r[g])?a:"0"<=g&&g<="7"?parseInt(d.substring(1),8):g==="u"||g==="x"?parseInt(d.substring(2),16):d.charCodeAt(1)}function j(d){if(d<32)return(d<16?"\\x0":"\\x")+d.toString(16);d=String.fromCharCode(d);return d==="\\"||d==="-"||d==="]"||d==="^"?"\\"+d:d}function c(d){var a=d.substring(1,d.length-1).match(/\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\S\s]|[^\\]/g),d=[],g=
a[0]==="^",b=["["];g&&b.push("^");for(var g=g?1:0,e=a.length;g<e;++g){var k=a[g];if(/\\[bdsw]/i.test(k))b.push(k);else{var k=f(k),h;g+2<e&&"-"===a[g+1]?(h=f(a[g+2]),g+=2):h=k;d.push([k,h]);h<65||k>122||(h<65||k>90||d.push([Math.max(65,k)|32,Math.min(h,90)|32]),h<97||k>122||d.push([Math.max(97,k)&-33,Math.min(h,122)&-33]))}}d.sort(function(d,a){return d[0]-a[0]||a[1]-d[1]});a=[];e=[];for(g=0;g<d.length;++g)k=d[g],k[0]<=e[1]+1?e[1]=Math.max(e[1],k[1]):a.push(e=k);for(g=0;g<a.length;++g)k=a[g],b.push(j(k[0])),
k[1]>k[0]&&(k[1]+1>k[0]&&b.push("-"),b.push(j(k[1])));b.push("]");return b.join("")}function w(d){for(var a=d.source.match(/\[(?:[^\\\]]|\\[\S\s])*]|\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\\d+|\\[^\dux]|\(\?[!:=]|[()^]|[^()[\\^]+/g),b=a.length,f=[],e=0,k=0;e<b;++e){var h=a[e];h==="("?++k:"\\"===h.charAt(0)&&(h=+h.substring(1))&&(h<=k?f[h]=-1:a[e]=j(h))}for(e=1;e<f.length;++e)-1===f[e]&&(f[e]=++u);for(k=e=0;e<b;++e)h=a[e],h==="("?(++k,f[k]||(a[e]="(?:")):"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=k&&
(a[e]="\\"+f[h]);for(e=0;e<b;++e)"^"===a[e]&&"^"!==a[e+1]&&(a[e]="");if(d.ignoreCase&&p)for(e=0;e<b;++e)h=a[e],d=h.charAt(0),h.length>=2&&d==="["?a[e]=c(h):d!=="\\"&&(a[e]=h.replace(/[A-Za-z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return a.join("")}for(var u=0,p=!1,i=!1,l=0,a=b.length;l<a;++l){var m=b[l];if(m.ignoreCase)i=!0;else if(/[a-z]/i.test(m.source.replace(/\\u[\da-f]{4}|\\x[\da-f]{2}|\\[^UXux]/gi,""))){p=!0;i=!1;break}}for(var r={b:8,t:9,n:10,v:11,
f:12,r:13},o=[],l=0,a=b.length;l<a;++l){m=b[l];if(m.global||m.multiline)throw Error(""+m);o.push("(?:"+w(m)+")")}return RegExp(o.join("|"),i?"gi":"g")}function R(b,f){function j(b){var a=b.nodeType;if(a==1){if(!c.test(b.className)){for(a=b.firstChild;a;a=a.nextSibling)j(a);a=b.nodeName.toLowerCase();if("br"===a||"li"===a)w[i]="\n",p[i<<1]=u++,p[i++<<1|1]=b}}else if(a==3||a==4)a=b.nodeValue,a.length&&(a=f?a.replace(/\r\n?/g,"\n"):a.replace(/[\t\n\r ]+/g," "),w[i]=a,p[i<<1]=u,u+=a.length,p[i++<<1|1]=
b)}var c=/(?:^|\s)nocode(?:\s|$)/,w=[],u=0,p=[],i=0;j(b);return{a:w.join("").replace(/\n$/,""),d:p}}function G(b,f,j,c){f&&(b={a:f,e:b},j(b),c.push.apply(c,b.g))}function x(b,f){function j(b){for(var i=b.e,l=[i,"pln"],a=0,m=b.a.match(w)||[],r={},o=0,d=m.length;o<d;++o){var z=m[o],g=r[z],t=void 0,e;if(typeof g==="string")e=!1;else{var k=c[z.charAt(0)];if(k)t=z.match(k[1]),g=k[0];else{for(e=0;e<u;++e)if(k=f[e],t=z.match(k[1])){g=k[0];break}t||(g="pln")}if((e=g.length>=5&&"lang-"===g.substring(0,5))&&
!(t&&typeof t[1]==="string"))e=!1,g="src";e||(r[z]=g)}k=a;a+=z.length;if(e){e=t[1];var h=z.indexOf(e),B=h+e.length;t[2]&&(B=z.length-t[2].length,h=B-e.length);g=g.substring(5);G(i+k,z.substring(0,h),j,l);G(i+k+h,e,H(g,e),l);G(i+k+B,z.substring(B),j,l)}else l.push(i+k,g)}b.g=l}var c={},w;(function(){for(var j=b.concat(f),i=[],l={},a=0,m=j.length;a<m;++a){var r=j[a],o=r[3];if(o)for(var d=o.length;--d>=0;)c[o.charAt(d)]=r;r=r[1];o=""+r;l.hasOwnProperty(o)||(i.push(r),l[o]=q)}i.push(/[\S\s]/);w=Q(i)})();
var u=f.length;return j}function v(b){var f=[],j=[];b.tripleQuotedStrings?f.push(["str",/^(?:'''(?:[^'\\]|\\[\S\s]|''?(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\S\s]|""?(?=[^"]))*(?:"""|$)|'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$))/,q,"'\""]):b.multiLineStrings?f.push(["str",/^(?:'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$)|`(?:[^\\`]|\\[\S\s])*(?:`|$))/,q,"'\"`"]):f.push(["str",/^(?:'(?:[^\n\r'\\]|\\.)*(?:'|$)|"(?:[^\n\r"\\]|\\.)*(?:"|$))/,q,"\"'"]);b.verbatimStrings&&j.push(["str",
/^@"(?:[^"]|"")*(?:"|$)/,q]);var c=b.hashComments;c&&(b.cStyleComments?(c>1?f.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,q,"#"]):f.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\n\r]*)/,q,"#"]),j.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,q])):f.push(["com",/^#[^\n\r]*/,q,"#"]));b.cStyleComments&&(j.push(["com",/^\/\/[^\n\r]*/,q]),j.push(["com",/^\/\*[\S\s]*?(?:\*\/|$)/,q]));b.regexLiterals&&
j.push(["lang-regex",/^(?:^^\.?|[+-]|[!=]={0,2}|#|%=?|&&?=?|\(|\*=?|[+-]=|->|\/=?|::?|<<?=?|>{1,3}=?|[,;?@[{~]|\^\^?=?|\|\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\s*(\/(?=[^*/])(?:[^/[\\]|\\[\S\s]|\[(?:[^\\\]]|\\[\S\s])*(?:]|$))+\/)/]);(c=b.types)&&j.push(["typ",c]);b=(""+b.keywords).replace(/^ | $/g,"");b.length&&j.push(["kwd",RegExp("^(?:"+b.replace(/[\s,]+/g,"|")+")\\b"),q]);f.push(["pln",/^\s+/,q," \r\n\t\u00a0"]);j.push(["lit",/^@[$_a-z][\w$@]*/i,q],
["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,q],["pln",/^[$_a-z][\w$@]*/i,q],["lit",/^(?:0x[\da-f]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+-]?\d+)?)[a-z]*/i,q,"0123456789"],["pln",/^\\[\S\s]?/,q],["pun",/^.[^\s\w"$'./@\\`]*/,q]);return x(f,j)}function I(b,f,j){function c(a){var b=a.nodeType;if(b==1&&!u.test(a.className))if("br"===a.nodeName)w(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)c(a);else if((b==3||b==4)&&j){var g=a.nodeValue,f=g.match(p);if(f)b=
g.substring(0,f.index),a.nodeValue=b,(g=g.substring(f.index+f[0].length))&&a.parentNode.insertBefore(i.createTextNode(g),a.nextSibling),w(a),b||a.parentNode.removeChild(a)}}function w(b){function f(a,b){var d=b?a.cloneNode(!1):a,h=a.parentNode;if(h){var h=f(h,1),g=a.nextSibling;h.appendChild(d);for(var c=g;c;c=g)g=c.nextSibling,h.appendChild(c)}return d}for(;!b.nextSibling;)if(b=b.parentNode,!b)return;for(var b=f(b.nextSibling,0),g;(g=b.parentNode)&&g.nodeType===1;)b=g;a.push(b)}for(var u=/(?:^|\s)nocode(?:\s|$)/,
p=/\r\n?|\n/,i=b.ownerDocument,l=i.createElement("li");b.firstChild;)l.appendChild(b.firstChild);for(var a=[l],m=0;m<a.length;++m)c(a[m]);f===(f|0)&&a[0].setAttribute("value",f);var r=i.createElement("ol");r.className="linenums";for(var f=Math.max(0,f-1|0)||0,m=0,o=a.length;m<o;++m)l=a[m],l.className="L"+(m+f)%10,l.firstChild||l.appendChild(i.createTextNode("\u00a0")),r.appendChild(l);b.appendChild(r)}function s(b,f){for(var j=f.length;--j>=0;){var c=f[j];E.hasOwnProperty(c)?C.console&&console.warn("cannot override language handler %s",
c):E[c]=b}}function H(b,f){if(!b||!E.hasOwnProperty(b))b=/^\s*</.test(f)?"default-markup":"default-code";return E[b]}function J(b){var f=b.h;try{var j=R(b.c,b.i),c=j.a;b.a=c;b.d=j.d;b.e=0;H(f,c)(b);var w=/\bMSIE\s(\d+)/.exec(navigator.userAgent),w=w&&+w[1]<=8,f=/\n/g,u=b.a,p=u.length,j=0,i=b.d,l=i.length,c=0,a=b.g,m=a.length,r=0;a[m]=p;var o,d;for(d=o=0;d<m;)a[d]!==a[d+2]?(a[o++]=a[d++],a[o++]=a[d++]):d+=2;m=o;for(d=o=0;d<m;){for(var s=a[d],g=a[d+1],t=d+2;t+2<=m&&a[t+1]===g;)t+=2;a[o++]=s;a[o++]=
g;d=t}a.length=o;var e=b.c,k;if(e)k=e.style.display,e.style.display="none";try{for(;c<l;){var h=i[c+2]||p,B=a[r+2]||p,t=Math.min(h,B),A=i[c+1],n;if(A.nodeType!==1&&(n=u.substring(j,t))){w&&(n=n.replace(f,"\r"));A.nodeValue=n;var v=A.ownerDocument,F=v.createElement("span");F.className=a[r+1];var y=A.parentNode;y.replaceChild(F,A);F.appendChild(A);j<h&&(i[c+1]=A=v.createTextNode(u.substring(t,h)),y.insertBefore(A,F.nextSibling))}j=t;j>=h&&(c+=2);j>=B&&(r+=2)}}finally{if(e)e.style.display=k}}catch(x){C.console&&
console.log(x&&x.stack?x.stack:x)}}var C=window,y=["break,continue,do,else,for,if,return,while"],D=[[y,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],K=[D,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
L=[D,"abstract,assert,boolean,byte,extends,final,finally,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],M=[L,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,internal,into,is,let,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var,virtual,where"],D=[D,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],
N=[y,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],O=[y,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],S=[y,"as,assert,const,copy,drop,enum,extern,fail,false,fn,impl,let,log,loop,match,mod,move,mut,priv,pub,pure,ref,self,static,struct,true,trait,type,unsafe,use"],y=[y,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],
P=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,T=/\S/,U=v({keywords:[K,M,D,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",N,O,y],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),E={};s(U,["default-code"]);s(x([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\S\s]*?(?:--\>|$)/],
["lang-",/^<\?([\S\s]+?)(?:\?>|$)/],["lang-",/^<%([\S\s]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\S\s]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\S\s]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\S\s]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),["default-markup","htm","html","mxml","xhtml","xml","xsl"]);s(x([["pln",/^\s+/,q," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,q,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w-.:]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],
["lang-uq.val",/^=\s*([^\s"'>]*(?:[^\s"'/>]|\/(?=\s)))/],["pun",/^[/<->]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^\s"'>]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",/^style\s*=\s*([^\s"'>]+)/i]]),["in.tag"]);s(x([],[["atv",/^[\S\s]+/]]),["uq.val"]);s(v({keywords:K,hashComments:!0,cStyleComments:!0,types:P}),["c","cc","cpp","cxx","cyc","m"]);s(v({keywords:"null,true,false"}),["json"]);
s(v({keywords:M,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:P}),["cs"]);s(v({keywords:L,cStyleComments:!0}),["java"]);s(v({keywords:y,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);s(v({keywords:N,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);s(v({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);s(v({keywords:O,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);s(v({keywords:D,cStyleComments:!0,regexLiterals:!0}),["javascript","js"]);s(v({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),
["coffee"]);s(v({keywords:S,cStyleComments:!0,multilineStrings:!0}),["rc","rs","rust"]);s(x([],[["str",/^[\S\s]+/]]),["regex"]);var V=C.PR={createSimpleLexer:x,registerLangHandler:s,sourceDecorator:v,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:C.prettyPrintOne=function(b,f,j){var c=document.createElement("div");
c.innerHTML="<pre>"+b+"</pre>";c=c.firstChild;j&&I(c,j,!0);J({h:f,j:j,c:c,i:1});return c.innerHTML},prettyPrint:C.prettyPrint=function(b,f){function j(){var k;for(var f=C.PR_SHOULD_USE_CONTINUATION?a.now()+250:Infinity;m<u.length&&a.now()<f;m++){var h=u[m],c=h.className;if(d.test(c)&&!v.test(c)){for(var i=!1,n=h.parentNode;n;n=n.parentNode)if(e.test(n.tagName)&&n.className&&d.test(n.className)){i=!0;break}if(!i){h.className+=" prettyprinted";var c=c.match(o),l;if(i=!c){for(var i=h,n=void 0,p=i.firstChild;p;p=
p.nextSibling)var x=p.nodeType,n=x===1?n?i:p:x===3?T.test(p.nodeValue)?i:n:n;i=(l=n===i?void 0:n)&&t.test(l.tagName)}i&&(c=l.className.match(o));c&&(c=c[1]);g.test(h.tagName)?i=1:(i=h.currentStyle,n=s.defaultView,k=(i=i?i.whiteSpace:n&&n.getComputedStyle?n.getComputedStyle(h,q).getPropertyValue("white-space"):0)&&"pre"===i.substring(0,3),i=k);(n=(n=h.className.match(/\blinenums\b(?::(\d+))?/))?n[1]&&n[1].length?+n[1]:!0:!1)&&I(h,n,i);r={h:c,c:h,j:n,i:i};J(r)}}}m<u.length?setTimeout(j,250):"function"===
typeof b&&b()}for(var c=f||document.body,s=c.ownerDocument||document,c=[c.getElementsByTagName("pre"),c.getElementsByTagName("code"),c.getElementsByTagName("xmp")],u=[],p=0;p<c.length;++p)for(var i=0,l=c[p].length;i<l;++i)u.push(c[p][i]);var c=q,a=Date;a.now||(a={now:function(){return+new Date}});var m=0,r,o=/\blang(?:uage)?-([\w.]+)(?!\S)/,d=/\bprettyprint\b/,v=/\bprettyprinted\b/,g=/pre|xmp/i,t=/^code$/i,e=/^(?:pre|code|xmp)$/i;j()}};typeof define==="function"&&define.amd&&define("google-code-prettify",
[],function(){return V})})();}()
