!function(){var q=null;window.PR_SHOULD_USE_CONTINUATION=!0;
(function(){function R(b){function c(e){var b=e.charCodeAt(0);if(b!==92)return b;var a=e.charAt(1);return(b=s[a])?b:"0"<=a&&a<="7"?parseInt(e.substring(1),8):a==="u"||a==="x"?parseInt(e.substring(2),16):e.charCodeAt(1)}function g(e){if(e<32)return(e<16?"\\x0":"\\x")+e.toString(16);e=String.fromCharCode(e);return e==="\\"||e==="-"||e==="]"||e==="^"?"\\"+e:e}function d(e){var b=e.substring(1,e.length-1).match(/\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\S\s]|[^\\]/g),e=[],a=
b[0]==="^",d=["["];a&&d.push("^");for(var a=a?1:0,f=b.length;a<f;++a){var h=b[a];if(/\\[bdsw]/i.test(h))d.push(h);else{var h=c(h),l;a+2<f&&"-"===b[a+1]?(l=c(b[a+2]),a+=2):l=h;e.push([h,l]);l<65||h>122||(l<65||h>90||e.push([Math.max(65,h)|32,Math.min(l,90)|32]),l<97||h>122||e.push([Math.max(97,h)&-33,Math.min(l,122)&-33]))}}e.sort(function(e,a){return e[0]-a[0]||a[1]-e[1]});b=[];f=[];for(a=0;a<e.length;++a)h=e[a],h[0]<=f[1]+1?f[1]=Math.max(f[1],h[1]):b.push(f=h);for(a=0;a<b.length;++a)h=b[a],d.push(g(h[0])),
h[1]>h[0]&&(h[1]+1>h[0]&&d.push("-"),d.push(g(h[1])));d.push("]");return d.join("")}function w(e){for(var a=e.source.match(/\[(?:[^\\\]]|\\[\S\s])*]|\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\\d+|\\[^\dux]|\(\?[!:=]|[()^]|[^()[\\^]+/g),b=a.length,c=[],f=0,h=0;f<b;++f){var l=a[f];l==="("?++h:"\\"===l.charAt(0)&&(l=+l.substring(1))&&(l<=h?c[l]=-1:a[f]=g(l))}for(f=1;f<c.length;++f)-1===c[f]&&(c[f]=++y);for(h=f=0;f<b;++f)l=a[f],l==="("?(++h,c[h]||(a[f]="(?:")):"\\"===l.charAt(0)&&(l=+l.substring(1))&&l<=h&&
(a[f]="\\"+c[l]);for(f=0;f<b;++f)"^"===a[f]&&"^"!==a[f+1]&&(a[f]="");if(e.ignoreCase&&n)for(f=0;f<b;++f)l=a[f],e=l.charAt(0),l.length>=2&&e==="["?a[f]=d(l):e!=="\\"&&(a[f]=l.replace(/[A-Za-z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return a.join("")}for(var y=0,n=!1,k=!1,i=0,a=b.length;i<a;++i){var j=b[i];if(j.ignoreCase)k=!0;else if(/[a-z]/i.test(j.source.replace(/\\u[\da-f]{4}|\\x[\da-f]{2}|\\[^UXux]/gi,""))){n=!0;k=!1;break}}for(var s={b:8,t:9,n:10,v:11,
f:12,r:13},m=[],i=0,a=b.length;i<a;++i){j=b[i];if(j.global||j.multiline)throw Error(""+j);m.push("(?:"+w(j)+")")}return RegExp(m.join("|"),k?"gi":"g")}function S(b,c){function g(b){var a=b.nodeType;if(a==1){if(!d.test(b.className)){for(a=b.firstChild;a;a=a.nextSibling)g(a);a=b.nodeName.toLowerCase();if("br"===a||"li"===a)w[k]="\n",n[k<<1]=y++,n[k++<<1|1]=b}}else if(a==3||a==4)a=b.nodeValue,a.length&&(a=c?a.replace(/\r\n?/g,"\n"):a.replace(/[\t\n\r ]+/g," "),w[k]=a,n[k<<1]=y,y+=a.length,n[k++<<1|1]=
b)}var d=/(?:^|\s)nocode(?:\s|$)/,w=[],y=0,n=[],k=0;g(b);return{a:w.join("").replace(/\n$/,""),d:n}}function H(b,c,g,d){c&&(b={a:c,e:b},g(b),d.push.apply(d,b.g))}function T(b){for(var c=void 0,g=b.firstChild;g;g=g.nextSibling)var d=g.nodeType,c=d===1?c?b:g:d===3?U.test(g.nodeValue)?b:c:c;return c===b?void 0:c}function A(b,c){function g(b){for(var k=b.e,i=[k,"pln"],a=0,j=b.a.match(w)||[],s={},m=0,e=j.length;m<e;++m){var z=j[m],v=s[z],u=void 0,f;if(typeof v==="string")f=!1;else{var h=d[z.charAt(0)];
if(h)u=z.match(h[1]),v=h[0];else{for(f=0;f<y;++f)if(h=c[f],u=z.match(h[1])){v=h[0];break}u||(v="pln")}if((f=v.length>=5&&"lang-"===v.substring(0,5))&&!(u&&typeof u[1]==="string"))f=!1,v="src";f||(s[z]=v)}h=a;a+=z.length;if(f){f=u[1];var l=z.indexOf(f),B=l+f.length;u[2]&&(B=z.length-u[2].length,l=B-f.length);v=v.substring(5);H(k+h,z.substring(0,l),g,i);H(k+h+l,f,I(v,f),i);H(k+h+B,z.substring(B),g,i)}else i.push(k+h,v)}b.g=i}var d={},w;(function(){for(var g=b.concat(c),k=[],i={},a=0,j=g.length;a<j;++a){var s=
g[a],m=s[3];if(m)for(var e=m.length;--e>=0;)d[m.charAt(e)]=s;s=s[1];m=""+s;i.hasOwnProperty(m)||(k.push(s),i[m]=q)}k.push(/[\S\s]/);w=R(k)})();var y=c.length;return g}function o(b){var c=[],g=[];b.tripleQuotedStrings?c.push(["str",/^(?:'''(?:[^'\\]|\\[\S\s]|''?(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\S\s]|""?(?=[^"]))*(?:"""|$)|'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$))/,q,"'\""]):b.multiLineStrings?c.push(["str",/^(?:'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$)|`(?:[^\\`]|\\[\S\s])*(?:`|$))/,
q,"'\"`"]):c.push(["str",/^(?:'(?:[^\n\r'\\]|\\.)*(?:'|$)|"(?:[^\n\r"\\]|\\.)*(?:"|$))/,q,"\"'"]);b.verbatimStrings&&g.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,q]);var d=b.hashComments;d&&(b.cStyleComments?(d>1?c.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,q,"#"]):c.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\n\r]*)/,q,"#"]),g.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,q])):c.push(["com",
/^#[^\n\r]*/,q,"#"]));b.cStyleComments&&(g.push(["com",/^\/\/[^\n\r]*/,q]),g.push(["com",/^\/\*[\S\s]*?(?:\*\/|$)/,q]));b.regexLiterals&&g.push(["lang-regex",/^(?:^^\.?|[+-]|[!=]={0,2}|#|%=?|&&?=?|\(|\*=?|[+-]=|->|\/=?|::?|<<?=?|>{1,3}=?|[,;?@[{~]|\^\^?=?|\|\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\s*(\/(?=[^*/])(?:[^/[\\]|\\[\S\s]|\[(?:[^\\\]]|\\[\S\s])*(?:]|$))+\/)/]);(d=b.types)&&g.push(["typ",d]);b=(""+b.keywords).replace(/^ | $/g,"");b.length&&g.push(["kwd",
RegExp("^(?:"+b.replace(/[\s,]+/g,"|")+")\\b"),q]);c.push(["pln",/^\s+/,q," \r\n\t\u00a0"]);g.push(["lit",/^@[$_a-z][\w$@]*/i,q],["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,q],["pln",/^[$_a-z][\w$@]*/i,q],["lit",/^(?:0x[\da-f]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+-]?\d+)?)[a-z]*/i,q,"0123456789"],["pln",/^\\[\S\s]?/,q],["pun",/^.[^\s\w"$'./@\\`]*/,q]);return A(c,g)}function J(b,c,g){function d(a){var b=a.nodeType;if(b==1&&!y.test(a.className))if("br"===a.nodeName)w(a),a.parentNode&&a.parentNode.removeChild(a);
else for(a=a.firstChild;a;a=a.nextSibling)d(a);else if((b==3||b==4)&&g){var c=a.nodeValue,j=c.match(n);if(j)b=c.substring(0,j.index),a.nodeValue=b,(c=c.substring(j.index+j[0].length))&&a.parentNode.insertBefore(k.createTextNode(c),a.nextSibling),w(a),b||a.parentNode.removeChild(a)}}function w(b){function c(a,b){var d=b?a.cloneNode(!1):a,e=a.parentNode;if(e){var e=c(e,1),g=a.nextSibling;e.appendChild(d);for(var j=g;j;j=g)g=j.nextSibling,e.appendChild(j)}return d}for(;!b.nextSibling;)if(b=b.parentNode,
!b)return;for(var b=c(b.nextSibling,0),d;(d=b.parentNode)&&d.nodeType===1;)b=d;a.push(b)}for(var y=/(?:^|\s)nocode(?:\s|$)/,n=/\r\n?|\n/,k=b.ownerDocument,i=k.createElement("li");b.firstChild;)i.appendChild(b.firstChild);for(var a=[i],j=0;j<a.length;++j)d(a[j]);c===(c|0)&&a[0].setAttribute("value",c);var s=k.createElement("ol");s.className="linenums";for(var c=Math.max(0,c-1|0)||0,j=0,m=a.length;j<m;++j)i=a[j],i.className="L"+(j+c)%10,i.firstChild||i.appendChild(k.createTextNode("\u00a0")),s.appendChild(i);
b.appendChild(s)}function p(b,c){for(var g=c.length;--g>=0;){var d=c[g];E.hasOwnProperty(d)?C.console&&console.warn("cannot override language handler %s",d):E[d]=b}}function I(b,c){if(!b||!E.hasOwnProperty(b))b=/^\s*</.test(c)?"default-markup":"default-code";return E[b]}function K(b){var c=b.h;try{var g=S(b.c,b.i),d=g.a;b.a=d;b.d=g.d;b.e=0;I(c,d)(b);var w=/\bMSIE\s(\d+)/.exec(navigator.userAgent),w=w&&+w[1]<=8,c=/\n/g,y=b.a,n=y.length,g=0,k=b.d,i=k.length,d=0,a=b.g,j=a.length,s=0;a[j]=n;var m,e;for(e=
m=0;e<j;)a[e]!==a[e+2]?(a[m++]=a[e++],a[m++]=a[e++]):e+=2;j=m;for(e=m=0;e<j;){for(var p=a[e],v=a[e+1],u=e+2;u+2<=j&&a[u+1]===v;)u+=2;a[m++]=p;a[m++]=v;e=u}a.length=m;var f=b.c,h;if(f)h=f.style.display,f.style.display="none";try{for(;d<i;){var l=k[d+2]||n,B=a[s+2]||n,u=Math.min(l,B),o=k[d+1],F;if(o.nodeType!==1&&(F=y.substring(g,u))){w&&(F=F.replace(c,"\r"));o.nodeValue=F;var t=o.ownerDocument,G=t.createElement("span");G.className=a[s+1];var r=o.parentNode;r.replaceChild(G,o);G.appendChild(o);g<l&&
(k[d+1]=o=t.createTextNode(y.substring(u,l)),r.insertBefore(o,G.nextSibling))}g=u;g>=l&&(d+=2);g>=B&&(s+=2)}}finally{if(f)f.style.display=h}}catch(x){C.console&&console.log(x&&x.stack||x)}}var C=window,x=["break,continue,do,else,for,if,return,while"],D=[[x,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],
L=[D,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],M=[D,"abstract,assert,boolean,byte,extends,final,finally,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],N=[M,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,internal,into,is,let,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var,virtual,where"],
D=[D,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],O=[x,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],P=[x,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],V=[x,"as,assert,const,copy,drop,enum,extern,fail,false,fn,impl,let,log,loop,match,mod,move,mut,priv,pub,pure,ref,self,static,struct,true,trait,type,unsafe,use"],
x=[x,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],Q=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,U=/\S/,W=o({keywords:[L,N,D,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",O,P,x],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),E={};p(W,["default-code"]);p(A([],
[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\S\s]*?(?:--\>|$)/],["lang-",/^<\?([\S\s]+?)(?:\?>|$)/],["lang-",/^<%([\S\s]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\S\s]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\S\s]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\S\s]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),["default-markup","htm","html","mxml","xhtml","xml","xsl"]);p(A([["pln",/^\s+/,q," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,
q,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w-.:]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^\s"'>]*(?:[^\s"'/>]|\/(?=\s)))/],["pun",/^[/<->]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^\s"'>]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",/^style\s*=\s*([^\s"'>]+)/i]]),["in.tag"]);p(A([],[["atv",/^[\S\s]+/]]),["uq.val"]);p(o({keywords:L,hashComments:!0,
cStyleComments:!0,types:Q}),["c","cc","cpp","cxx","cyc","m"]);p(o({keywords:"null,true,false"}),["json"]);p(o({keywords:N,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:Q}),["cs"]);p(o({keywords:M,cStyleComments:!0}),["java"]);p(o({keywords:x,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);p(o({keywords:O,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);p(o({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);p(o({keywords:P,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);p(o({keywords:D,cStyleComments:!0,regexLiterals:!0}),["javascript","js"]);p(o({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),
["coffee"]);p(o({keywords:V,cStyleComments:!0,multilineStrings:!0}),["rc","rs","rust"]);p(A([],[["str",/^[\S\s]+/]]),["regex"]);var X=C.PR={createSimpleLexer:A,registerLangHandler:p,sourceDecorator:o,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:C.prettyPrintOne=function(b,c,g){var d=document.createElement("div");
d.innerHTML="<pre>"+b+"</pre>";d=d.firstChild;g&&J(d,g,!0);K({h:c,j:g,c:d,i:1});return d.innerHTML},prettyPrint:C.prettyPrint=function(b,c){function g(){var l;for(var d=C.PR_SHOULD_USE_CONTINUATION?a.now()+250:Infinity;j<p.length&&a.now()<d;j++){var c=p[j],k=c.className;if(e.test(k)&&!x.test(k)){for(var i=!1,t=c.parentNode;t;t=t.parentNode)if(f.test(t.tagName)&&t.className&&e.test(t.className)){i=!0;break}if(!i){c.className+=" prettyprinted";for(var n=h,i=c;i=i.previousSibling;){var t=i.nodeType,
r=(t===7||t===8)&&i.nodeValue;if(r?!/^\??prettify\b/.test(r):t!==3||/\S/.test(i.nodeValue))break;if(r){n={};r.replace(/\b(\w+)=([\w%+\-.:]+)/g,function(a,b,c){n[b]=c});break}}i=n.lang;if(!i){var i=k.match(m),A;if(!i&&(A=T(c))&&u.test(A.tagName))i=A.className.match(m);i&&(i=i[1])}v.test(c.tagName)?t=1:(t=c.currentStyle,r=o.defaultView,l=(t=t?t.whiteSpace:r&&r.getComputedStyle?r.getComputedStyle(c,q).getPropertyValue("white-space"):0)&&"pre"===t.substring(0,3),t=l);r=n.linenums;if(!(r=r==="true"||+r))r=
(r=k.match(/\blinenums\b(?::(\d+))?/))?r[1]&&r[1].length?+r[1]:!0:!1;r&&J(c,r,t);s={h:i,c:c,j:r,i:t};K(s)}}}j<p.length?setTimeout(g,250):"function"===typeof b&&b()}for(var d=c||document.body,o=d.ownerDocument||document,d=[d.getElementsByTagName("pre"),d.getElementsByTagName("code"),d.getElementsByTagName("xmp")],p=[],n=0;n<d.length;++n)for(var k=0,i=d[n].length;k<i;++k)p.push(d[n][k]);var d=q,a=Date;a.now||(a={now:function(){return+new Date}});var j=0,s,m=/\blang(?:uage)?-([\w.]+)(?!\S)/,e=/\bprettyprint\b/,
x=/\bprettyprinted\b/,v=/pre|xmp/i,u=/^code$/i,f=/^(?:pre|code|xmp)$/i,h={};g()}};typeof define==="function"&&define.amd&&define("google-code-prettify",[],function(){return X})})();}()
