!function(){var r=null;
(function(){function X(g){function i(){try{J.doScroll("left")}catch(g){P(i,50);return}u("poll")}function u(i){if(!(i.type=="readystatechange"&&x.readyState!="complete")&&((i.type=="load"?p:x)[z](j+i.type,u,!1),!m&&(m=!0)))g.call(p,i.type||i)}var Y=x.addEventListener,m=!1,C=!0,t=Y?"addEventListener":"attachEvent",z=Y?"removeEventListener":"detachEvent",j=Y?"":"on";if(x.readyState=="complete")g.call(p,"lazy");else{if(x.createEventObject&&J.doScroll){try{C=!p.frameElement}catch(A){}C&&i()}x[t](j+"DOMContentLoaded",
u,!1);x[t](j+"readystatechange",u,!1);p[t](j+"load",u,!1)}}function Q(){S&&X(function(){var g=K.length;$(g?function(){for(var i=0;i<g;++i)(function(g){P(function(){p.exports[K[g]].apply(p,arguments)},0)})(i)}:void 0)})}for(var p=window,P=p.setTimeout,x=document,J=x.documentElement,L=x.head||x.getElementsByTagName("head")[0]||J,z="",A=x.scripts,m=A.length;--m>=0;){var M=A[m],T=M.src.match(/^[^#?]*\/run_prettify\.js(\?[^#]*)?(?:#.*)?$/);if(T){z=T[1]||"";M.parentNode.removeChild(M);break}}var S=!0,D=
[],N=[],K=[];z.replace(/[&?]([^&=]+)=([^&]+)/g,function(g,i,u){u=decodeURIComponent(u);i=decodeURIComponent(i);i=="autorun"?S=!/^[0fn]/i.test(u):i=="lang"?D.push(u):i=="skin"?N.push(u):i=="callback"&&K.push(u)});m=0;for(z=D.length;m<z;++m)(function(){var g=x.createElement("script");g.onload=g.onerror=g.onreadystatechange=function(){if(g&&(!g.readyState||/loaded|complete/.test(g.readyState)))g.onerror=g.onload=g.onreadystatechange=r,--R,R||P(Q,0),g.parentNode&&g.parentNode.removeChild(g),g=r};g.type=
"text/javascript";g.src="https://google-code-prettify.googlecode.com/svn/loader/lang-"+encodeURIComponent(D[m])+".js";L.insertBefore(g,L.firstChild)})(D[m]);for(var R=D.length,A=[],m=0,z=N.length;m<z;++m)A.push("https://google-code-prettify.googlecode.com/svn/loader/skins/"+encodeURIComponent(N[m])+".css");A.push("https://google-code-prettify.googlecode.com/svn/loader/prettify.css");(function(g){function i(m){if(m!==u){var p=x.createElement("link");p.rel="stylesheet";p.type="text/css";if(m+1<u)p.error=
p.onerror=function(){i(m+1)};p.href=g[m];L.appendChild(p)}}var u=g.length;i(0)})(A);var $=function(){window.PR_SHOULD_USE_CONTINUATION=!0;var g;(function(){function i(a){function d(e){var a=e.charCodeAt(0);if(a!==92)return a;var b=e.charAt(1);return(a=j[b])?a:"0"<=b&&b<="7"?parseInt(e.substring(1),8):b==="u"||b==="x"?parseInt(e.substring(2),16):e.charCodeAt(1)}function h(e){if(e<32)return(e<16?"\\x0":"\\x")+e.toString(16);e=String.fromCharCode(e);return e==="\\"||e==="-"||e==="]"||e==="^"?"\\"+e:
e}function c(e){var b=e.substring(1,e.length-1).match(/\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\S\s]|[^\\]/g),e=[],a=b[0]==="^",c=["["];a&&c.push("^");for(var a=a?1:0,f=b.length;a<f;++a){var l=b[a];if(/\\[bdsw]/i.test(l))c.push(l);else{var l=d(l),n;a+2<f&&"-"===b[a+1]?(n=d(b[a+2]),a+=2):n=l;e.push([l,n]);n<65||l>122||(n<65||l>90||e.push([Math.max(65,l)|32,Math.min(n,90)|32]),n<97||l>122||e.push([Math.max(97,l)&-33,Math.min(n,122)&-33]))}}e.sort(function(e,a){return e[0]-
a[0]||a[1]-e[1]});b=[];f=[];for(a=0;a<e.length;++a)l=e[a],l[0]<=f[1]+1?f[1]=Math.max(f[1],l[1]):b.push(f=l);for(a=0;a<b.length;++a)l=b[a],c.push(h(l[0])),l[1]>l[0]&&(l[1]+1>l[0]&&c.push("-"),c.push(h(l[1])));c.push("]");return c.join("")}function g(e){for(var a=e.source.match(/\[(?:[^\\\]]|\\[\S\s])*]|\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\\d+|\\[^\dux]|\(\?[!:=]|[()^]|[^()[\\^]+/g),b=a.length,d=[],f=0,l=0;f<b;++f){var n=a[f];n==="("?++l:"\\"===n.charAt(0)&&(n=+n.substring(1))&&(n<=l?d[n]=-1:a[f]=h(n))}for(f=
1;f<d.length;++f)-1===d[f]&&(d[f]=++i);for(l=f=0;f<b;++f)n=a[f],n==="("?(++l,d[l]||(a[f]="(?:")):"\\"===n.charAt(0)&&(n=+n.substring(1))&&n<=l&&(a[f]="\\"+d[n]);for(f=0;f<b;++f)"^"===a[f]&&"^"!==a[f+1]&&(a[f]="");if(e.ignoreCase&&F)for(f=0;f<b;++f)n=a[f],e=n.charAt(0),n.length>=2&&e==="["?a[f]=c(n):e!=="\\"&&(a[f]=n.replace(/[A-Za-z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return a.join("")}for(var i=0,F=!1,k=!1,I=0,b=a.length;I<b;++I){var o=a[I];if(o.ignoreCase)k=
!0;else if(/[a-z]/i.test(o.source.replace(/\\u[\da-f]{4}|\\x[\da-f]{2}|\\[^UXux]/gi,""))){F=!0;k=!1;break}}for(var j={b:8,t:9,n:10,v:11,f:12,r:13},q=[],I=0,b=a.length;I<b;++I){o=a[I];if(o.global||o.multiline)throw Error(""+o);q.push("(?:"+g(o)+")")}return RegExp(q.join("|"),k?"gi":"g")}function m(a,d){function h(a){var b=a.nodeType;if(b==1){if(!c.test(a.className)){for(b=a.firstChild;b;b=b.nextSibling)h(b);b=a.nodeName.toLowerCase();if("br"===b||"li"===b)g[k]="\n",F[k<<1]=i++,F[k++<<1|1]=a}}else if(b==
3||b==4)b=a.nodeValue,b.length&&(b=d?b.replace(/\r\n?/g,"\n"):b.replace(/[\t\n\r ]+/g," "),g[k]=b,F[k<<1]=i,i+=b.length,F[k++<<1|1]=a)}var c=/(?:^|\s)nocode(?:\s|$)/,g=[],i=0,F=[],k=0;h(a);return{a:g.join("").replace(/\n$/,""),d:F}}function p(a,d,h,c){d&&(a={a:d,e:a},h(a),c.push.apply(c,a.g))}function x(a){for(var d=void 0,h=a.firstChild;h;h=h.nextSibling)var c=h.nodeType,d=c===1?d?a:h:c===3?S.test(h.nodeValue)?a:d:d;return d===a?void 0:d}function C(a,d){function h(a){for(var k=a.e,i=[k,"pln"],b=
0,o=a.a.match(g)||[],m={},q=0,e=o.length;q<e;++q){var B=o[q],y=m[B],v=void 0,f;if(typeof y==="string")f=!1;else{var l=c[B.charAt(0)];if(l)v=B.match(l[1]),y=l[0];else{for(f=0;f<j;++f)if(l=d[f],v=B.match(l[1])){y=l[0];break}v||(y="pln")}if((f=y.length>=5&&"lang-"===y.substring(0,5))&&!(v&&typeof v[1]==="string"))f=!1,y="src";f||(m[B]=y)}l=b;b+=B.length;if(f){f=v[1];var n=B.indexOf(f),H=n+f.length;v[2]&&(H=B.length-v[2].length,n=H-f.length);y=y.substring(5);p(k+l,B.substring(0,n),h,i);p(k+l+n,f,A(y,
f),i);p(k+l+H,B.substring(H),h,i)}else i.push(k+l,y)}a.g=i}var c={},g;(function(){for(var h=a.concat(d),k=[],j={},b=0,o=h.length;b<o;++b){var m=h[b],q=m[3];if(q)for(var e=q.length;--e>=0;)c[q.charAt(e)]=m;m=m[1];q=""+m;j.hasOwnProperty(q)||(k.push(m),j[q]=r)}k.push(/[\S\s]/);g=i(k)})();var j=d.length;return h}function t(a){var d=[],h=[];a.tripleQuotedStrings?d.push(["str",/^(?:'''(?:[^'\\]|\\[\S\s]|''?(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\S\s]|""?(?=[^"]))*(?:"""|$)|'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$))/,
r,"'\""]):a.multiLineStrings?d.push(["str",/^(?:'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$)|`(?:[^\\`]|\\[\S\s])*(?:`|$))/,r,"'\"`"]):d.push(["str",/^(?:'(?:[^\n\r'\\]|\\.)*(?:'|$)|"(?:[^\n\r"\\]|\\.)*(?:"|$))/,r,"\"'"]);a.verbatimStrings&&h.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,r]);var c=a.hashComments;c&&(a.cStyleComments?(c>1?d.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,r,"#"]):d.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\n\r]*)/,
r,"#"]),h.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,r])):d.push(["com",/^#[^\n\r]*/,r,"#"]));a.cStyleComments&&(h.push(["com",/^\/\/[^\n\r]*/,r]),h.push(["com",/^\/\*[\S\s]*?(?:\*\/|$)/,r]));a.regexLiterals&&h.push(["lang-regex",/^(?:^^\.?|[+-]|[!=]={0,2}|#|%=?|&&?=?|\(|\*=?|[+-]=|->|\/=?|::?|<<?=?|>{1,3}=?|[,;?@[{~]|\^\^?=?|\|\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\s*(\/(?=[^*/])(?:[^/[\\]|\\[\S\s]|\[(?:[^\\\]]|\\[\S\s])*(?:]|$))+\/)/]);
(c=a.types)&&h.push(["typ",c]);c=(""+a.keywords).replace(/^ | $/g,"");c.length&&h.push(["kwd",RegExp("^(?:"+c.replace(/[\s,]+/g,"|")+")\\b"),r]);d.push(["pln",/^\s+/,r," \r\n\t\u00a0"]);c="^.[^\\s\\w.$@'\"`/\\\\]*";a.regexLiterals&&(c+="(?!s*/)");h.push(["lit",/^@[$_a-z][\w$@]*/i,r],["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,r],["pln",/^[$_a-z][\w$@]*/i,r],["lit",/^(?:0x[\da-f]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+-]?\d+)?)[a-z]*/i,r,"0123456789"],["pln",/^\\[\S\s]?/,r],["pun",RegExp(c),r]);
return C(d,h)}function z(a,d,h){function c(a){var b=a.nodeType;if(b==1&&!i.test(a.className))if("br"===a.nodeName)g(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)c(a);else if((b==3||b==4)&&h){var d=a.nodeValue,j=d.match(m);if(j)b=d.substring(0,j.index),a.nodeValue=b,(d=d.substring(j.index+j[0].length))&&a.parentNode.insertBefore(k.createTextNode(d),a.nextSibling),g(a),b||a.parentNode.removeChild(a)}}function g(a){function c(a,b){var d=b?a.cloneNode(!1):a,e=
a.parentNode;if(e){var e=c(e,1),h=a.nextSibling;e.appendChild(d);for(var g=h;g;g=h)h=g.nextSibling,e.appendChild(g)}return d}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;for(var a=c(a.nextSibling,0),d;(d=a.parentNode)&&d.nodeType===1;)a=d;b.push(a)}for(var i=/(?:^|\s)nocode(?:\s|$)/,m=/\r\n?|\n/,k=a.ownerDocument,j=k.createElement("li");a.firstChild;)j.appendChild(a.firstChild);for(var b=[j],o=0;o<b.length;++o)c(b[o]);d===(d|0)&&b[0].setAttribute("value",d);var p=k.createElement("ol");p.className=
"linenums";for(var d=Math.max(0,d-1|0)||0,o=0,q=b.length;o<q;++o)j=b[o],j.className="L"+(o+d)%10,j.firstChild||j.appendChild(k.createTextNode("\u00a0")),p.appendChild(j);a.appendChild(p)}function j(a,d){for(var h=d.length;--h>=0;){var c=d[h];U.hasOwnProperty(c)?V.console&&console.warn("cannot override language handler %s",c):U[c]=a}}function A(a,d){if(!a||!U.hasOwnProperty(a))a=/^\s*</.test(d)?"default-markup":"default-code";return U[a]}function D(a){var d=a.h;try{var h=m(a.c,a.i),c=h.a;a.a=c;a.d=
h.d;a.e=0;A(d,c)(a);var g=/\bMSIE\s(\d+)/.exec(navigator.userAgent),g=g&&+g[1]<=8,d=/\n/g,j=a.a,i=j.length,h=0,k=a.d,p=k.length,c=0,b=a.g,o=b.length,t=0;b[o]=i;var q,e;for(e=q=0;e<o;)b[e]!==b[e+2]?(b[q++]=b[e++],b[q++]=b[e++]):e+=2;o=q;for(e=q=0;e<o;){for(var x=b[e],y=b[e+1],v=e+2;v+2<=o&&b[v+1]===y;)v+=2;b[q++]=x;b[q++]=y;e=v}b.length=q;var f=a.c,l;if(f)l=f.style.display,f.style.display="none";try{for(;c<p;){var n=k[c+2]||i,H=b[t+2]||i,v=Math.min(n,H),E=k[c+1],W;if(E.nodeType!==1&&(W=j.substring(h,
v))){g&&(W=W.replace(d,"\r"));E.nodeValue=W;var Z=E.ownerDocument,s=Z.createElement("span");s.className=b[t+1];var z=E.parentNode;z.replaceChild(s,E);s.appendChild(E);h<n&&(k[c+1]=E=Z.createTextNode(j.substring(v,n)),z.insertBefore(E,s.nextSibling))}h=v;h>=n&&(c+=2);h>=H&&(t+=2)}}finally{if(f)f.style.display=l}}catch(w){V.console&&console.log(w&&w.stack||w)}}var V=window,G=["break,continue,do,else,for,if,return,while"],O=[[G,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],
"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],J=[O,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],K=[O,"abstract,assert,boolean,byte,extends,final,finally,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],
L=[K,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,internal,into,is,let,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var,virtual,where"],O=[O,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],M=[G,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],
N=[G,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],R=[G,"as,assert,const,copy,drop,enum,extern,fail,false,fn,impl,let,log,loop,match,mod,move,mut,priv,pub,pure,ref,self,static,struct,true,trait,type,unsafe,use"],G=[G,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],Q=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,
S=/\S/,T=t({keywords:[J,L,O,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",M,N,G],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),U={};j(T,["default-code"]);j(C([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\S\s]*?(?:--\>|$)/],["lang-",/^<\?([\S\s]+?)(?:\?>|$)/],["lang-",/^<%([\S\s]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",
/^<xmp\b[^>]*>([\S\s]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\S\s]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\S\s]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),["default-markup","htm","html","mxml","xhtml","xml","xsl"]);j(C([["pln",/^\s+/,r," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,r,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w-.:]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^\s"'>]*(?:[^\s"'/>]|\/(?=\s)))/],["pun",/^[/<->]+/],
["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^\s"'>]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",/^style\s*=\s*([^\s"'>]+)/i]]),["in.tag"]);j(C([],[["atv",/^[\S\s]+/]]),["uq.val"]);j(t({keywords:J,hashComments:!0,cStyleComments:!0,types:Q}),["c","cc","cpp","cxx","cyc","m"]);j(t({keywords:"null,true,false"}),["json"]);j(t({keywords:L,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:Q}),
["cs"]);j(t({keywords:K,cStyleComments:!0}),["java"]);j(t({keywords:G,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);j(t({keywords:M,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);j(t({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);j(t({keywords:N,
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);j(t({keywords:O,cStyleComments:!0,regexLiterals:!0}),["javascript","js"]);j(t({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);j(t({keywords:R,cStyleComments:!0,multilineStrings:!0}),["rc","rs","rust"]);
j(C([],[["str",/^[\S\s]+/]]),["regex"]);var X=V.PR={createSimpleLexer:C,registerLangHandler:j,sourceDecorator:t,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:function(a,d,h){var c=document.createElement("div");c.innerHTML="<pre>"+a+"</pre>";c=c.firstChild;h&&z(c,h,!0);D({h:d,j:h,c:c,i:1});return c.innerHTML},
prettyPrint:g=g=function(a,d){function h(){for(var d=V.PR_SHOULD_USE_CONTINUATION?b.now()+250:Infinity;o<j.length&&b.now()<d;o++){for(var c=j[o],i=l,m=c;m=m.previousSibling;){var k=m.nodeType,s=(k===7||k===8)&&m.nodeValue;if(s?!/^\??prettify\b/.test(s):k!==3||/\S/.test(m.nodeValue))break;if(s){i={};s.replace(/\b(\w+)=([\w%+\-.:]+)/g,function(a,b,c){i[b]=c});break}}m=c.className;if((i!==l||e.test(m))&&!t.test(m)){k=!1;for(s=c.parentNode;s;s=s.parentNode)if(f.test(s.tagName)&&s.className&&e.test(s.className)){k=
!0;break}if(!k){c.className+=" prettyprinted";k=i.lang;if(!k){var k=m.match(q),u;if(!k&&(u=x(c))&&v.test(u.tagName))k=u.className.match(q);k&&(k=k[1])}if(y.test(c.tagName))s=1;else var s=c.currentStyle,w=g.defaultView,s=(s=s?s.whiteSpace:w&&w.getComputedStyle?w.getComputedStyle(c,r).getPropertyValue("white-space"):0)&&"pre"===s.substring(0,3);w=i.linenums;if(!(w=w==="true"||+w))w=(w=m.match(/\blinenums\b(?::(\d+))?/))?w[1]&&w[1].length?+w[1]:!0:!1;w&&z(c,w,s);p={h:k,c:c,j:w,i:s};D(p)}}}o<j.length?
P(h,250):"function"===typeof a&&a()}for(var c=d||document.body,g=c.ownerDocument||document,c=[c.getElementsByTagName("pre"),c.getElementsByTagName("code"),c.getElementsByTagName("xmp")],j=[],i=0;i<c.length;++i)for(var k=0,m=c[i].length;k<m;++k)j.push(c[i][k]);var c=r,b=Date;b.now||(b={now:function(){return+new Date}});var o=0,p,q=/\blang(?:uage)?-([\w.]+)(?!\S)/,e=/\bprettyprint\b/,t=/\bprettyprinted\b/,y=/pre|xmp/i,v=/^code$/i,f=/^(?:pre|code|xmp)$/i,l={};h()}};typeof define==="function"&&define.amd&&
define("google-code-prettify",[],function(){return X})})();return g}();R||P(Q,0)})();}()
